version: "3"
services:
  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    #depends_on:
    # - db
  api-server:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    #depends_on:
    #  - db
  #db:
  #  volumes:
  #    - slack_db:/data/db
  #  image: mongo:latest
  #  ports:
  #    - "27017:27017"
#volumes:
#   slack_db: