---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-app
spec:
  type: LoadBalancer
  selector:
    app: react-frontend-app
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-app
  labels:
    app: react-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend-app
  template:
    metadata:
      labels:
        app: react-frontend-app
    spec:
      containers:
        - name: react-frontend-app
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/food-store-repo/react-frontend-img:latest
