---
apiVersion: v1
kind: Service
metadata:
  name: react-backend
spec:
  type: LoadBalancer
  selector:
    app: react-backend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-backend
  labels:
    app: react-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-backend
  template:
    metadata:
      labels:
        app: react-backend
    spec:
      containers:
        - name: react-backend
          image: asia-east1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-repo/react-backend-img:latest
