name: Deploy food-store backend

on:
  push:
    branches:
      - "main"
    paths:
      - backend/**
      - .github/workflows/backend-build-and-deploy.yaml
      - backend-resources.yaml

env:
  SERVICE: react-backend-cloud-run-service # Cloud Run service name
  REGION: us-central1 # Cloud Run service region
  VERSION_SHA_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: 'Create .env file'
        working-directory: ./backend
        run: |
          touch .env
          echo MONGO_URI=${{ secrets.SECRET_MONGO_URI }} >> .env
          echo JWT_SECRET=${{ secrets.SECRET_JWT_SECRET }} >> .env
          echo PORT=${{ secrets.SECRET_PORT }} >> .env
          cat .env

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          TAG: ${{ github.sha }}
        working-directory: ./backend
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-backend-img:$TAG .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-backend-img:$TAG

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          IMAGE_SHA_TAG: ${{ github.sha }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-east4
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" backend-resources.yaml
          sed -i "s/IMAGE_SHA_TAG/$IMAGE_SHA_TAG/g" backend-resources.yaml
          kubectl apply -f backend-resources.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/food-store-02/react-backend-img:${{ env.VERSION_SHA_TAG }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}