name: Deploy frontend

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
      - .github/workflows/frontend-build-and-deploy.yaml
      - frontend-resources.yaml

env:
  TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        working-directory: ./frontend
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-frontend-img:${{ env.TAG }} .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-frontend-img:${{ env.TAG }}

      - name: deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-east4
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" frontend-resources.yaml
          sed -i "s/IMAGE_SHA_TAG/${{ env.TAG }}/g" frontend-resources.yaml
          kubectl apply -f frontend-resources.yaml

      - name: deploy to cloud run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/food-store-02/react-frontend-img:${{ env.TAG }}
          service: react-frontend-cloud-run-service
          region: us-central1

      # If required, use the Cloud Run url output in later steps
      - name: show output
        run: echo ${{ steps.deploy.outputs.url }}