name: Deploy food-store frontend

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
      - .github/workflows/frontend-build-and-deploy.yaml
      - frontend-resources.yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          TAG: ${{ github.sha }}
        working-directory: ./frontend
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-frontend-img:$TAG .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/food-store-02/react-frontend-img:$TAG

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          IMAGE_SHA_TAG: ${{ github.sha }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-east4
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" frontend-resources.yaml
          sed -i "s/IMAGE_SHA_TAG/$IMAGE_SHA_TAG/g" frontend-resources.yaml
          kubectl apply -f frontend-resources.yaml
